### PR TITLE
Add everything needed for simdjson.rs

### PR DESCRIPTION
**Pull request by Licenser**
WIP: implement everything needed for simd-json.rs

### CODE REVIEW

**Comment by Licenser** [comment]
see https://github.com/simd-lite/simdjson-rs/pull/39

**Comment by sunnygleason** [comment]
@Licenser I'm running into a bunch of issues with fields in std::arch::aarch64::uint8x16_t and friends being private. I'm wondering, should we totally cut the dependency between simd-lite and std::arch::{arm, aarch64}?

**Comment by Licenser** [comment]
That's what users got to see, the types are private so we have to assume that's the case. We can use mem transmute (or the related load instruction) and vget_lane or store instructions to access.

If we copy arm and aarch over then we can't use the upstream intrinsics any more since they get in conflict :( and rust will ge `"noooo! Found uint8x16_t but expected uint8x16_t"` which would be sad.

**Comment by sunnygleason** [comment]
Yeah I'm in the "oh noo" situation right now trying to adapt simdjson-rs, it's not a great dev experience using mixed std:arch and these additional functions. I think eventually we'd want
to eliminate the cross-package dependency so this is a drop-in, would make life soooo much
easier. Let me prototype a bit and we can compare notes...

**Comment by Licenser** [comment]
look at #39 in simdjson-rs I've translate it already but ams stuck with a few bugs now.

**Comment by sunnygleason** [comment]
nice! I think the issue is a discrepancy with the vtst instruction (see the other PR), I ran into this a couple days ago. (if it's the same issue)

**Comment by sunnygleason** [comment]
@Licenser did you find the bug? I think I might have it:

https://github.com/simd-lite/simdjson-rs/pull/40/commits/8875cff3a93c5380f00917e335896a096a2229b5#diff-e3cc34fc9e09211fc01983167aaf86d7R47

(signed versus unsigned subtraction in utf8check, we had an error in the previous intrinsics)

PS. ignore all the intrinsics changes, that's just me bisecting the problem

**Review by sunnygleason — APPROVED** [review]

**Comment by Licenser** [comment]
Huzza!

**Pull request merged**
